name: changelog

on:
    release:
        types:
            - released

permissions: write-all

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: none

            -   name: Git setup
                if: success()
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"

            -   name: Update
                uses: stefanzweifel/changelog-updater-action@v1
                if: success()
                with:
                    release-date: ${{ steps.release_date.outputs.date }}
                    release-notes: ${{ github.event.release.body }}
                    latest-version: ${{ github.event.release.tag_name }}
                    compare-url-target-revision: ${{ github.event.release.target_commitish }}
                    path-to-changelog: docs/prologue/changelog/4.x.md

            -   name: Storing
                id: changelog
                if: success()
                run: |
                    IS_DIRTY=1

                    { git add . && git commit -a -m "🧾 Update CHANGELOG"; } || IS_DIRTY=0

                    echo ::set-output name=is_dirty::${IS_DIRTY}

            -   name: Push changes
                uses: ad-m/github-push-action@master
                if: success() && steps.changelog.outputs.is_dirty == 1
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}
